# Generated by Django 4.1.3 on 2022-11-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('student_unique_ID', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
            ],
        ),
    ]
